Switch DSSE provider to go-securesystemslib
sigstore/rekor pull request #442
Opened 2021-09-28 18:21 UTC by adityasaky

Signed-off-by: Aditya Sirish <aditya@saky.in>

#### Summary

Switches from using `github.com/in-toto/in-toto-golang/pkg/ssl` to `github.com/secure-systems-lab/go-securesystemslib/dsse`.

#### Ticket Link

N/A.

#### Release Note

```release-note
Uses new provider for DSSE.
```

2021-09-28 18:23 UTC, adityasaky commented
I should note that we're planning to deprecate `in_toto.NewSSLSigner` in favour of `in_toto.NewDSSESigner`. Happy to submit a patch when that's live. :smile:

2021-09-30 11:46 UTC, lukehinds commented
> I should note that we're planning to deprecate `in_toto.NewSSLSigner` in favour of `in_toto.NewDSSESigner`. Happy to submit a patch when that's live. smile

yes please do

2021-09-30 11:47 UTC, lukehinds approved these changes

2021-09-30 11:47 UTC, lukehinds requested changes
I think the tests need porting to:

`tests/e2e_test.go:351:19: undefined: in_toto.PredicateProvenanceV01`

2021-10-03 19:37 UTC, dlorenc approved these changes

2021-10-03 19:37 UTC, merged